<?php

namespace App\Http\Controllers\Api\V1\Swagger;

use App\Http\Controllers\Controller;
use OpenApi\Annotations as OA;

/**
 * @OA\Get(
 *     path="/api/v1/qrs/{id}",
 *     summary="Получение данных о конкретном QR-профиле",
 *     tags={"QR Profile"},
 *     @OA\Parameter(
 *         description="ID QR-профиля",
 *         in="path",
 *         name="id",
 *         required=true,
 *         example=1
 *     ),
 *     @OA\Response(
 *         response="200",
 *         description="Success",
 *         @OA\JsonContent(
 *             @OA\Property(property="data", type="object",
 *                 @OA\Property(property="id", type="integer", example=1, description="ID клиента, с которым будет связан QR-профиль человека"),
 *                 @OA\Property(property="country", type="string", example="Украина", description="Название страны, в которой был рождён человек из QR-профиля"),
 *                 @OA\Property(property="city", type="string", example="Днепр", description="Название города, в котором был рождён человек из QR-профиля"),
 *                 @OA\Property(property="birth_date", type="string", example="25.05.1985", description="Дата рождения человека из QR-профиля"),
 *                 @OA\Property(property="death_date", type="string", example="16.11.2020", description="Дата смерти человека из QR-профиля"),
 *                 @OA\Property(property="full_name", type="string", example="Тестовая Мария Тестовна", description="ФИО человека из QR-профиля"),
 *                 @OA\Property(property="firstname", type="string", example="Мария", description="Имя человека из QR-профиля"),
 *                 @OA\Property(property="lastname", type="string", example="Тестовая", description="Фамилия человека из QR-профиля"),
 *                 @OA\Property(property="surname", type="string", example="Тестовна", description="Отчество человека из QR-профиля"),
 *                 @OA\Property(property="cause_death", type="string", example="Сердечный приступ", description="Причина смерти человека из QR-профиля")),
 *                 @OA\Property(property="profession", type="string", example="Секретарь", description="Профессия человека из QR-профиля"),
 *                 @OA\Property(property="hobbies", type="string", example="Рисование, велосипед, кино", description="Хобби человека из QR-профиля"),
 *                 @OA\Property(property="biography", type="string", example="Мария — творческая натура, обожающая рисовать утренние пейзажи и городские силуэты. В свободное время любит покататься на велосипеде, исследуя улочки города. Часто посещает кинотеатры и наслаждается просмотром разнообразных фильмов. В течение нескольких лет работала в качестве секретаря в уютном офисе, где находила радость в организации рабочего процесса и поддержке коллег.", description="Биография человека из QR-профиля"),
 *                 @OA\Property(property="last_wish", type="string", example="Мария желала, чтобы ее последнее мгновение было окружено уютом, мелодиями любимой музыки и в объятиях близких людей.", description="Последнее желание человека из QR-профиля"),
 *                 @OA\Property(property="favourite_music_artist", type="string", example="The Beatles", description="Любимая музыкальная группа человека из QR-профиля"),
 *                 @OA\Property(property="link", type="string", example="https://google.com", description="Ссылка на внешний источник"),
 *                 @OA\Property(property="geo_latitude", type="string", example="-37.397325", description="Географическая широта места захоронения [где находится QR-код]"),
 *                 @OA\Property(property="geo_longitude", type="string", example="92.499078", description="Географическая долгота места захоронения [где находится QR-код]"),
 *                 @OA\Property(property="photo_file_name", type="string", example="1703167599.jpg"),
 *                 @OA\Property(property="photo_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/1703167599.jpg"),
 *                 @OA\Property(property="voice_message_file_name", type="string", example="test_voice.mp3"),
 *                 @OA\Property(property="voice_message_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/test_voice.mp3"),
 *                 @OA\Property(property="qr_code_file_name", type="string", example="qr_code.png"),
 *                 @OA\Property(property="qr_code_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/qr_code.png"),
 *             ),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=400,
 *         description="Bad request",
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="Not Found 404",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="QR Profile not found."),
 *             @OA\Property(property="id", type="integer", example="1"),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Внутренняя ошибка сервера",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Something went wrong."),
 *         ),
 *      ),
 * ),
 * @OA\Post(
 *     path="/api/v1/qrs",
 *     summary="Создание нового QR-профиля (необходим Bearer Token)",
 *     tags={"QR Profile"},
 *     security={{ "bearerAuth": {} }},
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="multipart/form-data",
 *             @OA\Schema(
 *                 required={"id_client", "id_country", "id_city", "firstname", "lastname"},
 *                 @OA\Property(property="id_client", type="integer", example=1, description="ID клиента, с которым будет связан QR-профиль человека"),
 *                 @OA\Property(property="id_country", type="integer", example=1, description="ID страны, в которой был рождён человек из QR-профиля"),
 *                 @OA\Property(property="id_city", type="integer", example=1, description="ID города, в котором был рождён человек из QR-профиля"),
 *                 @OA\Property(property="firstname", type="string", example="Мария", description="Имя человека из QR-профиля"),
 *                 @OA\Property(property="lastname", type="string", example="Тестовая", description="Фамилия человека из QR-профиля"),
 *                 @OA\Property(property="surname", type="string", example="Тестовна", description="Отчество человека из QR-профиля"),
 *                 @OA\Property(property="birth_date", type="string", format="date", example="1985-05-25", description="Дата рождения человека из QR-профиля"),
 *                 @OA\Property(property="death_date", type="string", format="date", example="2020-11-16", description="Дата смерти человека из QR-профиля"),
 *                 @OA\Property(property="cause_death", type="string", example="Сердечный приступ", description="Причина смерти человека из QR-профиля"),
 *                 @OA\Property(property="profession", type="string", example="Секретарь", description="Профессия человека из QR-профиля"),
 *                 @OA\Property(property="hobbies", type="string", example="Рисование, велосипед, кино", description="Хобби человека из QR-профиля"),
 *                 @OA\Property(property="biography", type="string", example="Мария — творческая натура...", description="Биография человека из QR-профиля"),
 *                 @OA\Property(property="last_wish", type="string", example="Мария желала...", description="Последнее желание человека из QR-профиля"),
 *                 @OA\Property(property="favourite_music_artist", type="string", example="The Beatles", description="Любимая музыкальная группа человека из QR-профиля"),
 *                 @OA\Property(property="link", type="string", format="url", example="https://google.com", description="Ссылка на внешний источник"),
 *                 @OA\Property(property="geo_latitude", type="string", example="-37.397325", description="Географическая широта места захоронения [где будет находится QR-код]"),
 *                 @OA\Property(property="geo_longitude", type="string", example="92.499078", description="Географическая долгота места захоронения [где будет находится QR-код]"),
 *                 @OA\Property(property="photo_file", type="string", format="binary", description="Фотография для QR-профиля. Допускаются форматы: jpg, jpeg, png. Максимальный размер файла 4 МБ."),
 *                 @OA\Property(property="voice_message_file", type="string", format="binary", description="Файл аудиозаписи для QR-профиля. Допускаются форматы: mp3, wav, ogg, flac. Максимальный размер файла 10 МБ."),
 *             ),
 *         ),
 *     ),
 *     @OA\Response(
 *         response="201",
 *         description="QR-профиль успешно создан",
 *         @OA\JsonContent(
 *             @OA\Property(property="data", type="object",
 *                 @OA\Property(property="id", type="integer", example=1),
 *                 @OA\Property(property="country", type="string", example="Украина"),
 *                 @OA\Property(property="city", type="string", example="Днепр"),
 *                 @OA\Property(property="birth_date", type="string", example="1985-05-25"),
 *                 @OA\Property(property="death_date", type="string", example="2020-11-16"),
 *                 @OA\Property(property="full_name", type="string", example="Тестовая Мария Тестовна"),
 *                 @OA\Property(property="firstname", type="string", example="Мария"),
 *                 @OA\Property(property="lastname", type="string", example="Тестовая"),
 *                 @OA\Property(property="surname", type="string", example="Тестовна"),
 *                 @OA\Property(property="cause_death", type="string", example="Сердечный приступ"),
 *                 @OA\Property(property="profession", type="string", example="Секретарь"),
 *                 @OA\Property(property="hobbies", type="string", example="Рисование, велосипед, кино"),
 *                 @OA\Property(property="biography", type="string", example="Мария — творческая натура..."),
 *                 @OA\Property(property="last_wish", type="string", example="Мария желала..."),
 *                 @OA\Property(property="favourite_music_artist", type="string", example="The Beatles"),
 *                 @OA\Property(property="link", type="string", example="https://google.com"),
 *                 @OA\Property(property="geo_latitude", type="string", example="-37.397325"),
 *                 @OA\Property(property="geo_longitude", type="string", example="92.499078"),
 *                 @OA\Property(property="photo_file_name", type="string", example="1703167599.jpg"),
 *                 @OA\Property(property="photo_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/1703167599.jpg"),
 *                 @OA\Property(property="voice_message_file_name", type="string", example="test_voice.mp3"),
 *                 @OA\Property(property="voice_message_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/test_voice.mp3"),
 *                 @OA\Property(property="qr_code_file_name", type="string", example="qr_code.png"),
 *                 @OA\Property(property="qr_code_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/qr_code.png"),
 *             ),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Неавторизованный",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Unauthenticated."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="Невалидные данные",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Unable to create a Qr Profile due to incorrect data."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Внутренняя ошибка сервера",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Something went wrong."),
 *         ),
 *     ),
 * ),
 * @OA\Post(
 *     path="/api/v1/qrs/{id}",
 *     summary="Обновление существующего QR-профиля (необходим Bearer Token)",
 *     tags={"QR Profile"},
 *     security={{ "bearerAuth": {} }},
 *     @OA\Parameter(description="ID QR-профиля", in="path", name="id", required=true, example=3),
 *     @OA\RequestBody(
 *         required=true,
 *         @OA\MediaType(
 *             mediaType="multipart/form-data",
 *             @OA\Schema(
 *                 required={"id_client"},
 *                 @OA\Property(property="id_client", type="integer", example=1, description="ID клиента, с которым связан QR-профиль человека"),
 *                 @OA\Property(property="id_country", type="integer", example=1, description="ID страны, в которой был рождён человек из QR-профиля"),
 *                 @OA\Property(property="id_city", type="integer", example=1, description="ID города, в котором был рождён человек из QR-профиля"),
 *                 @OA\Property(property="firstname", type="string", example="Мария", description="Имя человека из QR-профиля"),
 *                 @OA\Property(property="lastname", type="string", example="Тестовая", description="Фамилия человека из QR-профиля"),
 *                 @OA\Property(property="surname", type="string", example="Тестовна", description="Отчество человека из QR-профиля"),
 *                 @OA\Property(property="birth_date", type="string", format="date", example="1985-05-25", description="Дата рождения человека из QR-профиля"),
 *                 @OA\Property(property="death_date", type="string", format="date", example="2020-11-16", description="Дата смерти человека из QR-профиля"),
 *                 @OA\Property(property="cause_death", type="string", example="Сердечный приступ", description="Причина смерти человека из QR-профиля"),
 *                 @OA\Property(property="profession", type="string", example="Секретарь", description="Профессия человека из QR-профиля"),
 *                 @OA\Property(property="hobbies", type="string", example="Рисование, велосипед, кино", description="Хобби человека из QR-профиля"),
 *                 @OA\Property(property="biography", type="string", example="Мария — творческая натура...", description="Биография человека из QR-профиля"),
 *                 @OA\Property(property="last_wish", type="string", example="Мария желала...", description="Последнее желание человека из QR-профиля"),
 *                 @OA\Property(property="favourite_music_artist", type="string", example="The Beatles", description="Любимая музыкальная группа человека из QR-профиля"),
 *                 @OA\Property(property="link", type="string", format="url", example="https://google.com", description="Ссылка на внешний источник"),
 *                 @OA\Property(property="geo_latitude", type="string", example="-37.397325", description="Географическая широта места захоронения [где будет находится QR-код]"),
 *                 @OA\Property(property="geo_longitude", type="string", example="92.499078", description="Географическая долгота места захоронения [где будет находится QR-код]"),
 *                 @OA\Property(property="photo_file", type="string", format="binary", description="Фотография для QR-профиля. Допускаются форматы: jpg, jpeg, png. Максимальный размер файла 4 МБ."),
 *                 @OA\Property(property="voice_message_file", type="string", format="binary", description="Файл аудиозаписи для QR-профиля. Допускаются форматы: mp3, wav, ogg, flac. Максимальный размер файла 10 МБ."),
 *             ),
 *         ),
 *     ),
 *     @OA\Response(
 *         response="200",
 *         description="QR-профиль успешно обновлён",
 *         @OA\JsonContent(
 *             @OA\Property(property="data", type="object",
 *                 @OA\Property(property="id", type="integer", example=1),
 *                 @OA\Property(property="country", type="string", example="Украина"),
 *                 @OA\Property(property="city", type="string", example="Днепр"),
 *                 @OA\Property(property="birth_date", type="string", example="1985-05-25"),
 *                 @OA\Property(property="death_date", type="string", example="2020-11-16"),
 *                 @OA\Property(property="full_name", type="string", example="Тестовая Мария Тестовна"),
 *                 @OA\Property(property="firstname", type="string", example="Мария"),
 *                 @OA\Property(property="lastname", type="string", example="Тестовая"),
 *                 @OA\Property(property="surname", type="string", example="Тестовна"),
 *                 @OA\Property(property="cause_death", type="string", example="Сердечный приступ"),
 *                 @OA\Property(property="profession", type="string", example="Секретарь"),
 *                 @OA\Property(property="hobbies", type="string", example="Рисование, велосипед, кино"),
 *                 @OA\Property(property="biography", type="string", example="Мария — творческая натура..."),
 *                 @OA\Property(property="last_wish", type="string", example="Мария желала..."),
 *                 @OA\Property(property="favourite_music_artist", type="string", example="The Beatles"),
 *                 @OA\Property(property="link", type="string", example="https://google.com"),
 *                 @OA\Property(property="geo_latitude", type="string", example="-37.397325"),
 *                 @OA\Property(property="geo_longitude", type="string", example="92.499078"),
 *                 @OA\Property(property="photo_file_name", type="string", example="1703167599.jpg"),
 *                 @OA\Property(property="photo_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/1703167599.jpg"),
 *                 @OA\Property(property="voice_message_file_name", type="string", example="test_voice.mp3"),
 *                 @OA\Property(property="voice_message_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/test_voice.mp3"),
 *                 @OA\Property(property="qr_code_file_name", type="string", example="qr_code.png"),
 *                 @OA\Property(property="qr_code_file_path", type="string", example="https://crm-qr-laravel.loc/storage/qr/1/qr_code.png"),
 *             ),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Неавторизованный",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Unauthenticated."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=403,
 *         description="Входящий ID клиента не совпадает с текущим ID клиента QR-профиля",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Access Error. You cannot modify this QR Profile."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="Невалидные данные",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Unable to update a Qr Profile due to incorrect data."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Внутренняя ошибка сервера",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Something went wrong."),
 *         ),
 *     ),
 *     security={{"bearerAuth":{}}}
 * ),
 * @OA\Delete(
 *     path="/api/v1/qrs/{id}",
 *     summary="Удаление существующего QR-профиля (необходим Bearer Token)",
 *     tags={"QR Profile"},
 *     security={{ "bearerAuth": {} }},
 *     @OA\Parameter(description="ID QR-профиля", in="path", name="id", required=true, example=1),
 *     @OA\Response(
 *         response="204",
 *         description="QR-профиль успешно удалён",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="integer", example=false),
 *             @OA\Property(property="message", type="string", example="QR Profile deleted successfully."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=401,
 *         description="Неавторизованный",
 *         @OA\JsonContent(
 *             @OA\Property(property="message", type="string", example="Unauthenticated."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=404,
 *         description="Not Found 404",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="QR Profile not found."),
 *             @OA\Property(property="id", type="integer", example="1"),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=422,
 *         description="Невалидные данные",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Unable to delete a Qr Profile due to incorrect data."),
 *         ),
 *     ),
 *     @OA\Response(
 *         response=500,
 *         description="Внутренняя ошибка сервера",
 *         @OA\JsonContent(
 *             @OA\Property(property="error", type="bool", example=true),
 *             @OA\Property(property="message", type="string", example="Something went wrong."),
 *         ),
 *     ),
 * ),
 */
class QrProfileSwaggerController extends Controller
{
}
